<?php
/**
* @file
* A description of what your module does.
*/

/**
 * Implements hook_theme().
 */
function svg_icon_theme() {

  return array(
    'svg_icon' => array(
      'render element' => 'element'
    ),
    'svg_icon_text' => array(
      'render element' => 'element'
    )
  );
}

/**
 * Implements hook_preprocess_HOOK().
 */
function svg_icon_preprocess_svg_icon(&$variables) {

  $variables['icon_id'] = $variables['element']['#icon_id'];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function svg_icon_preprocess_svg_icon_text(&$variables) {

  $variables['icon_right'] = $variables['element']['#icon_right'];
  $variables['hide_label'] = $variables['element']['#hide_label'];
}