svg_sprite.svg_sprite.*:
  type: config_entity
  label: 'SVG icon'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    svg_sprite:
      type: mapping
      label: 'SVG Sprite'
      mapping:
        fid:
          type: string
          label: 'FID'
